# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: 100% Test Coverage

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      GITHUB_ACTION: true

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0' # Not needed with a .ruby-version file

    - name: Install Gems
      run: rake bundle

    - name: Run tests
      run: rake coverage

    - name: Assert 100% Test Coverage
      run: >
        ruby -e "require('json') && 
        (rate = JSON.parse(File.read('coverage/.last_run.json'))['result']['line'].to_i) &&
        (rate == 100 ? exit(0) : exit(rate))"
